[package]
name = "check-file-dups"
version = "0.1.0"
edition = "2024"
rust-version = "1.90"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
blake3 = "1.5"
walkdir = "2.5"
indicatif = "0.17"
anyhow = "1.0"
log = "0.4"
env_logger = "0.11"
