[package]
name = "check-file-dups"
version = "0.1.0"
edition = "2024"
rust-version = "1.90"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
sha2 = "0.10"
walkdir = "2.5"
indicatif = "0.17"
anyhow = "1.0"
